Resources:
  VisitorCountAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  VisitorCountLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: 'visitorCounter'
    
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'visitorCounter'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
